/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.guiCalculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Sabrina Vargas
 */
public class CalculadoraGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName());

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        plValores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtValor1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtValor2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnReestablecer = new javax.swing.JButton();
        rbtnFahrenheit = new javax.swing.JRadioButton();
        rbtnCelsius = new javax.swing.JRadioButton();
        btnConvertir = new javax.swing.JButton();
        txtValorGrados = new javax.swing.JTextField();
        lbl3 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plTitulo.setBackground(new java.awt.Color(102, 102, 102));
        plTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calculadora Básica");
        plTitulo.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 254, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive - Instituto Tecnológico de Las Américas (ITLA)\\Documents\\icons8-math-simple-small (1)\\icons8-math-64.png")); // NOI18N
        jLabel1.setText("lbl2");
        plTitulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 60));

        getContentPane().add(plTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 80));

        plValores.setBackground(new java.awt.Color(153, 153, 153));
        plValores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Valor1");
        plValores.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 20));

        txtValor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValor1ActionPerformed(evt);
            }
        });
        txtValor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor1KeyTyped(evt);
            }
        });
        plValores.add(txtValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 100, 40));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Valor1");
        plValores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 20));

        txtValor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtValor2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValor2KeyTyped(evt);
            }
        });
        plValores.add(txtValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Respuesta:");
        plValores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        txtRespuesta.setEditable(false);
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        plValores.add(txtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 60));

        getContentPane().add(plValores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 270, 310));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, -1));

        btnRestar.setText("Restar");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, -1));

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, -1));

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 90, -1));

        btnReestablecer.setText("Reestablecer");
        btnReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerActionPerformed(evt);
            }
        });
        jPanel1.add(btnReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 110, 40));

        rbtnFahrenheit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnFahrenheit.setText("Fahrenheit");
        rbtnFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFahrenheitActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnFahrenheit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        rbtnCelsius.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtnCelsius.setText("Celsius");
        rbtnCelsius.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                rbtnCelsiusComponentAdded(evt);
            }
        });
        rbtnCelsius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnCelsiusMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rbtnCelsiusMouseExited(evt);
            }
        });
        rbtnCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCelsiusActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnCelsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 90, 40));

        txtValorGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorGradosActionPerformed(evt);
            }
        });
        txtValorGrados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorGradosKeyTyped(evt);
            }
        });
        jPanel1.add(txtValorGrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, 40));

        lbl3.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Convertidor De Grados");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lbl5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("Selecciona la medida por convertir:");
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 290, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        validarCampos();
        sumarValores();
    }//GEN-LAST:event_btnSumarActionPerformed
        
    private void validarCampos(){
        if(txtValor1.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 1, porque el campo esta vacio. ");
            txtValor1.requestFocus();
        } else if(txtValor2.getText().trim().length() <= 0){
            JOptionPane.showMessageDialog(null, "Favor ingresar valor 2, porque el campo esta vacio. ");
            txtValor1.requestFocus();
        }
    } 
    
    private void sumarValores(){
        Calculadora cal = new Calculadora ();
        Double respuesta = cal.sumar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
    }
    
    private void limpiarCampos(){
        txtValor1.setText("");
        txtValor2.setText("");
        txtRespuesta.setText("");
        txtValor1.requestFocus();
    }
    
    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        validarCampos();
        restarValores();
    }//GEN-LAST:event_btnRestarActionPerformed

     private void restarValores(){
        Calculadora cal = new Calculadora ();
        Double respuesta = cal.restar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
     }
     
    private void btnReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnReestablecerActionPerformed

    private void txtValor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor1KeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null, "Favor ingresar números para la realizar la operación. ");
            evt.consume();
        }        
    }//GEN-LAST:event_txtValor1KeyTyped

    private void txtValor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValor2KeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null, "Favor ingresar números para la realizar la operación. ");
            evt.consume();
        }
    }//GEN-LAST:event_txtValor2KeyTyped

    private void txtValor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValor1ActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        validarCampos();
        multiplicarValores();
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        validarCampos();
        dividirValores();// TODO add your handling code here:
    }//GEN-LAST:event_btnDividirActionPerformed

    private void txtValorGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorGradosActionPerformed

    private void rbtnFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFahrenheitActionPerformed
        if (rbtnFahrenheit.isSelected()) {
        rbtnCelsius.setSelected(false);
    } else {
        rbtnFahrenheit.setSelected(true);
    }
    }//GEN-LAST:event_rbtnFahrenheitActionPerformed

    private void rbtnCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCelsiusActionPerformed
        if (rbtnCelsius.isSelected()) {
        rbtnFahrenheit.setSelected(false);
    } else {
        rbtnCelsius.setSelected(true);
    }
    }//GEN-LAST:event_rbtnCelsiusActionPerformed

    private void txtValorGradosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorGradosKeyTyped
        char numeros = evt.getKeyChar();
        if((numeros < '0' || numeros > '9') && (numeros < ',' || numeros > '.')){
            JOptionPane.showMessageDialog(null, "Favor ingresar un valor para la conversión. ");
            evt.consume();
        }
    }//GEN-LAST:event_txtValorGradosKeyTyped

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        convertirGrados();
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void rbtnCelsiusComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_rbtnCelsiusComponentAdded
        
    }//GEN-LAST:event_rbtnCelsiusComponentAdded

 
    
    private void rbtnCelsiusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCelsiusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCelsiusMouseClicked

    private void rbtnCelsiusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCelsiusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCelsiusMouseExited

    private void convertirGrados(){
    ConvertidorGrados cg = new ConvertidorGrados();
    int valor = Integer.parseInt(txtValorGrados.getText());

    if (rbtnCelsius.isSelected()) {
       int resultado = cg.convertidorCelsiusAFahrenheit(valor);
       JOptionPane.showMessageDialog(null, valor + " °C = " + resultado + " °F");
    } else if (rbtnFahrenheit.isSelected()) {
        int resultado = cg.convertidorFahrenheitACelsius(valor);
        JOptionPane.showMessageDialog(null, valor + " °F = " + resultado + " °C");
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione una opción");
    }
    }
    
     private void dividirValores(){
        Calculadora cal = new Calculadora ();
        Double respuesta = cal.dividir(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
        
     }    
    
     private void multiplicarValores(){
        Calculadora cal = new Calculadora ();
        Double respuesta = cal.multiplicar(Double.parseDouble(txtValor1.getText()), Double.parseDouble(txtValor2.getText()));
        txtRespuesta.setText(respuesta +"");
        
     }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnReestablecer;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plTitulo;
    private javax.swing.JPanel plValores;
    private javax.swing.JRadioButton rbtnCelsius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtValor1;
    private javax.swing.JTextField txtValor2;
    private javax.swing.JTextField txtValorGrados;
    // End of variables declaration//GEN-END:variables

}
